CREATE VIEW [dbo].[vINF005] AS 


SELECT 
	CAST(NULL AS VARCHAR(100))		AS IND_UID
,	CAST(NULL AS VARCHAR(6)) 		AS MAP_PLAT_LEAK_NO
,	CAST(NULL AS VARCHAR(16))		AS LEAK_NO
,	CAST(GETDATE() AS DATE)			AS RPT_DATE
,	CAST(GETDATE() AS TIME)			AS RPT_TIME
,	CAST(GETDATE() AS DATE)			AS READ_DATE
,	CAST(GETDATE() AS TIME)			AS READ_TIME
,	CAST(NULL AS VARCHAR(4))		AS READ_LANID
,	CAST(NULL AS DATE)				AS SPVR_APPROVAL_DATE
,	CAST(NULL AS VARCHAR(4))		AS SPVR_LANID
,	CAST(NULL AS VARCHAR(30))		AS FLOC
,	CAST(NULL AS VARCHAR(8))		AS MWC
,	CAST(NULL AS VARCHAR(10))		AS DIV
,	CAST(NULL AS VARCHAR(2))		AS PIPE_TYPE
,	CAST(NULL AS VARCHAR(12))		AS ROUTE_NO
,	CAST(NULL AS DECIMAL(15,12))	AS LAT
,	CAST(NULL AS DECIMAL(15,12))	AS LONG
,	CAST(NULL AS DECIMAL(4,2))		AS ACCURACY_FT
,	CAST(NULL AS VARCHAR(10))		AS HOUSE_NO
,	CAST(NULL AS VARCHAR(60))		AS STREET
,	CAST(NULL AS VARCHAR(20))		AS APT
,	CAST(NULL AS VARCHAR(40))		AS CITY
,	CAST(NULL AS VARCHAR(3))		AS COUNTY
,	CAST(NULL AS VARCHAR(2))		AS FAC_TYPE
,	CAST(NULL AS CHAR(1))			AS ABV_BLW
,	CAST(NULL AS VARCHAR(2))		AS INT_LK_SRC
,	CAST(NULL AS VARCHAR(2))		AS RPT_BY
,	CAST(NULL AS VARCHAR(500))		AS DESC_READ_LOC
,	CAST(NULL AS CHAR(1))			AS WL_2_WL
,	CAST(NULL AS VARCHAR(2))		AS SORL
,	CAST(NULL AS VARCHAR(32))		AS SORL_OTHER
,	CAST(NULL AS CHAR(1))			AS WN_5FT
,	CAST(NULL AS CHAR(1))			AS SUSP_COP
,	CAST(NULL AS VARCHAR(25))		AS FND_SERAL_NO
,	CAST(NULL AS VARCHAR(2))		AS INST_TYPE_CODE
,	CAST(NULL AS VARCHAR(25))		AS GRD_SERAL_NO
,	CAST(NULL AS DECIMAL(8,3))		AS PCT_GAS
,	CAST(NULL AS VARCHAR(2))		AS GRADE
,	CAST(NULL AS VARCHAR(2))		AS INFO_CODE
,	CAST(NULL AS CHAR(1))			AS HCA
,	CAST(NULL AS VARCHAR(100))		AS LOC_REMRK
,	CAST(NULL AS VARCHAR(18))		AS STA_BEGIN
,	CAST(NULL AS VARCHAR(18))		AS STA_END
,	CAST(NULL AS VARCHAR(4))		AS HCA_CONST_ID
,	CAST(NULL AS VARCHAR(4))		AS HCA_DISTR_ID
,	CAST(NULL AS VARCHAR(4))		AS HCA_PIPEL_ID
,	CAST(NULL AS VARCHAR(150))		AS IND_PHOTO1
,	CAST(NULL AS VARCHAR(150))		AS IND_PHOTO2
,	CAST(NULL AS VARCHAR(150))		AS IND_PHOTO3