



CREATE Procedure [dbo].[spAutomaticTaskOut]
AS


select distinct MasterLeakLogUID into #InProgressMMLUID from tgAssetAddressIndication where StatusType = 'In Progress' and ActiveFlag = 1

Update aai set ActiveFlag = 0
From [dbo].[tgAssetAddressIndication] aai
Join #InProgressMMLUID ip on aai.MasterLeakLogUID = ip.MasterLeakLogUID
Where aai.ActiveFlag = 1 and aai.StatusType = 'In Progress'


Insert Into [dbo].[tgAssetAddressIndication]
(
	AssetAddressIndicationUID,
	AssetAddressUID,
	InspectionRequestUID,
	MapGridUID,
	MasterLeakLogUID,
	ProjectID,
	SourceID,
	CreatedUserUID,
	ModifiedUserUID,
	SrcDTLT,
	SrcOpenDTLT,
	SrcClosedDTLT,
	GPSType,
	GPSSentence,
	Latitude,
	Longitude,
	SHAPE,
	Comments,
	RevisionComments,
	Revision,
	ActiveFlag,
	StatusType,
	ManualMapPlat,
	PipelineType,
	SurveyType,
	Map,
	Plat,
	RecordedMap,
	RecordedPlat,
	RecordedBlock,
	LandmarkType,
	Route,
	Line,
	HouseNoNAFlag,
	HouseNo,
	Street1,
	City,
	DescriptionReadingLocation,
	County,
	CountyCode,
	FacilityType,
	LocationType,
	InitialLeakSourceType,
	ReportedByType,
	LeakNo,
	SAPNo,
	PavedType,
	SORLType,
	SORLOther,
	Within5FeetOfBuildingType,
	SuspectedCopperType,
	EquipmentFoundByUID,
	FoundBy,
	FoundBySerialNumber,
	InstrumentTypeGradeByType,
	EquipmentGradeByUID,
	GradeBy,
	GradeBySerialNumber,
	ReadingGrade,
	GradeType,
	InfoCodesType,
	PotentialHCAType,
	Grade2PlusRequested,
	TwoPercentOrLessSuspectCopperFlag,
	LeakDownGradedFlag,
	HCAConstructionSupervisorUserUID,
	HCADistributionPlanningEngineerUserUID,
	HCAPipelineEngineerUserUID,
	Photo1,
	Photo2,
	Photo3,
	OptionalData1,
	OptionalData2,
	OptionalData3,
	OptionalData4,
	OptionalData5,
	OptionalData6,
	OptionalData7,
	OptionalData8,
	OptionalData9,
	OptionalData10,
	OptionalData11,
	OptionalData12,
	ApprovedFlag,
	ApprovedByUserUID,
	ApprovedDTLT,
	SubmittedFlag,
	SubmittedStatusType,
	SubmittedUserUID,
	SubmittedDTLT,
	ResponseStatusType,
	ResponseComments,
	ResponceErrorComments,
	ResponseDTLT,
	CompletedFlag,
	CompletedDTLT,
	AboveBelowGroundType,
	FoundDateTime,
	GPSSource,
	GPSTime,
	FixQuality,
	NumberOfSatellites,
	HDOP,
	AltitudemetersAboveMeanSeaLevel,
	HeightOfGeoid,
	TimeSecondsSinceLastDGPS,
	ChecksumData,
	Bearing,
	Speed,
	GPSStatus,
	NumberOfGPSAttempts,
	ActivityUID,
	AssetInspectionUID,
	MapPlatLeakNumber,
	LockedFlag
)
Select
	aai.AssetAddressIndicationUID,
	AssetAddressUID,
	InspectionRequestUID,
	MapGridUID,
	MasterLeakLogUID,
	ProjectID,
	'System', --SourceID,
	CreatedUserUID,
	'User_System_Automation', --ModifiedUserUID,
	getdate(), --SrcDTLT,
	SrcOpenDTLT,
	SrcClosedDTLT,
	GPSType,
	GPSSentence,
	Latitude,
	Longitude,
	SHAPE,
	Comments,
	'Changed To Pending via Nightly Automated Task Out Process', --RevisionComments,
	NextRev.NextRevision,
	1, --ActiveFlag,
	'Pending', --StatusType,
	ManualMapPlat,
	PipelineType,
	SurveyType,
	Map,
	Plat,
	RecordedMap,
	RecordedPlat,
	RecordedBlock,
	LandmarkType,
	Route,
	Line,
	HouseNoNAFlag,
	HouseNo,
	Street1,
	City,
	DescriptionReadingLocation,
	County,
	CountyCode,
	FacilityType,
	LocationType,
	InitialLeakSourceType,
	ReportedByType,
	LeakNo,
	SAPNo,
	PavedType,
	SORLType,
	SORLOther,
	Within5FeetOfBuildingType,
	SuspectedCopperType,
	EquipmentFoundByUID,
	FoundBy,
	FoundBySerialNumber,
	InstrumentTypeGradeByType,
	EquipmentGradeByUID,
	GradeBy,
	GradeBySerialNumber,
	ReadingGrade,
	GradeType,
	InfoCodesType,
	PotentialHCAType,
	Grade2PlusRequested,
	TwoPercentOrLessSuspectCopperFlag,
	LeakDownGradedFlag,
	HCAConstructionSupervisorUserUID,
	HCADistributionPlanningEngineerUserUID,
	HCAPipelineEngineerUserUID,
	Photo1,
	Photo2,
	Photo3,
	OptionalData1,
	OptionalData2,
	OptionalData3,
	OptionalData4,
	OptionalData5,
	OptionalData6,
	OptionalData7,
	OptionalData8,
	OptionalData9,
	OptionalData10,
	OptionalData11,
	OptionalData12,
	ApprovedFlag,
	ApprovedByUserUID,
	ApprovedDTLT,
	SubmittedFlag,
	SubmittedStatusType,
	SubmittedUserUID,
	SubmittedDTLT,
	ResponseStatusType,
	ResponseComments,
	ResponceErrorComments,
	ResponseDTLT,
	CompletedFlag,
	CompletedDTLT,
	AboveBelowGroundType,
	FoundDateTime,
	GPSSource,
	GPSTime,
	FixQuality,
	NumberOfSatellites,
	HDOP,
	AltitudemetersAboveMeanSeaLevel,
	HeightOfGeoid,
	TimeSecondsSinceLastDGPS,
	ChecksumData,
	Bearing,
	Speed,
	GPSStatus,
	NumberOfGPSAttempts,
	ActivityUID,
	AssetInspectionUID,
	MapPlatLeakNumber,
	0 --LockedFlag
From [dbo].[tgAssetAddressIndication] aai
Join (select AssetAddressIndicationUID, Count(*) NextRevision from [dbo].[tgAssetAddressIndication] aai
	Join #InProgressMMLUID ip on aai.MasterLeakLogUID = ip.MasterLeakLogUID
	Group By AssetAddressIndicationUID) NextRev on aai.AssetAddressIndicationUID = NextRev.AssetAddressIndicationUID and aai.Revision = NextRev.NextRevision - 1
	Where aai.StatusType = 'In Progress'

--Drop Table #InProgressMMLUID

select distinct MasterLeakLogUID into #InProgressIS  from tInspectionService where StatusType = 'In Progress' and ActiveFlag = 1 and PlaceHolderFlag = 1

Update [is] set ActiveFlag = 0
From [dbo].[tInspectionService] [is]
Join #InProgressIS ip on [is].MasterLeakLogUID = ip.MasterLeakLogUID
Where [is].ActiveFlag = 1 and [is].StatusType <> 'Deleted' and PlaceHolderFlag = 1


Insert Into [dbo].[tInspectionService]
(
	InspectionServicesUID, 
	MasterLeakLogUID, 
	MapGridUID, 
	InspectionRequestUID, 
	InspectionEquipmentUID, 
	ProjectID, 
	SourceID, 
	CreatedUserUID, 
	ModifiedUserUID, 
	SrcDTLT, 
	--SrvDTLT, 
	--SrvDTLTOffset, 
	Comments, 
	RevisionComments, 
	Revision, 
	ActiveFlag, 
	StatusType, 
	EquipmentType, 
	InstrumentType, 
	SerialNumber, 
	CalibrationLevel, 
	CalibrationVerificationFlag, 
	WindSpeedStart, 
	WindSpeedEnd, 
	EquipmentModeType, 
	EstimatedFeet, 
	EstimatedServices, 
	EstimatedHours, 
	ApprovedFlag, 
	ApprovedByUserUID, 
	ApprovedDTLT, 
	SubmittedFlag, 
	SubmittedStatusType, 
	SubmittedUserUID, 
	SubmittedDTLT, 
	ResponseStatusType, 
	Response, 
	ResponceErrorDescription, 
	ResponseDTLT, 
	CompletedFlag, 
	CompletedDTLT, 
	SurveyMode, 
	PlaceHolderFlag,
	LockedFlag
	--,
	--TaskOutUID
)
Select
	[is].InspectionServicesUID, 
	[is].MasterLeakLogUID, 
	MapGridUID, 
	InspectionRequestUID, 
	InspectionEquipmentUID, 
	[is].ProjectID, 
	'System', --SourceID, 
	[is].CreatedUserUID, 
	'User_System_Automation', --ModifiedUserUID, 
	getdate(), --SrcDTLT, 
	--SrvDTLT, 
	--SrvDTLTOffset, 
	[is].Comments, 
	'Changed To Active Record via Nightly Automated Task Out Process', --RevisionComments, 
	NextRev.NextRevision, 
	1, --ActiveFlag, 
	'Pending', --StatusType, 
	ie.EquipmentType, --   [is].EquipmentType, 
	InstrumentType, 
	ie.SerialNumber, --  [is].SerialNumber, 
	CalibrationLevel, 
	[is].CalibrationVerificationFlag, 
	WindSpeedStart, 
	WindSpeedEnd, 
	EquipmentModeType, 
	0, --EstimatedFeet, 
	0, --EstimatedServices, 
	0, --EstimatedHours, 
	ApprovedFlag, 
	ApprovedByUserUID, 
	ApprovedDTLT, 
	[is].SubmittedFlag, 
	[is].SubmittedStatusType, 
	[is].SubmittedUserUID, 
	[is].SubmittedDTLT, 
	ResponseStatusType, 
	Response, 
	ResponceErrorDescription, 
	ResponseDTLT, 
	CompletedFlag, 
	CompletedDTLT, 
	SurveyMode, 
	0, --PlaceHolderFlag
	0--, --LockedFlag
	--'TO_' + [is].SourceID + '_TF_' + Format(getdate(), 'yyyyMMddhhmmss', 'en-US') + Right(ie.InspecitonEquipmentUID, 4)
From [dbo].[tInspectionService] [is]
Join (select InspectionServicesUID, Count(*) NextRevision from [dbo].[tInspectionService] [is]
		Join #InProgressIS ip on [is].MasterLeakLogUID = ip.MasterLeakLogUID
		Group By InspectionServicesUID) NextRev on [is].InspectionServicesUID = NextRev.InspectionServicesUID and [is].Revision = NextRev.NextRevision - 1
Left Join tInspectionsEquipment ie on [is].InspectionEquipmentUID = ie.InspecitonEquipmentUID
Where [is].StatusType <> 'Deleted' and PlaceHolderFlag = 1


Update [is] set TaskOutUID = [dbo].[CreateTaskOutUID]([is].tInspectionServicesID, [is].SourceID, Right([is].InspectionServicesUID, 4), getdate())
From [dbo].[tInspectionService] [is]
Join #InProgressIS ip on [is].MasterLeakLogUID = ip.MasterLeakLogUID
Where [is].ActiveFlag = 1 and [is].StatusType <> 'Deleted' and PlaceHolderFlag = 0 and [is].TaskOutUID is null





Drop table #InProgressMMLUID
Drop Table #InProgressIS