CREATE TABLE [dbo].[ActivityTb] (
    [ActivityID]                              INT                IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ActivityUID]                             VARCHAR (100)      NULL,
    [ActivityProjectID]                       INT                NULL,
    [ActivitySourceID]                        VARCHAR (100)      NULL,
    [ActivityCreatedUserUID]                  VARCHAR (100)      NULL,
    [ActivityModifiedUserUID]                 VARCHAR (100)      NULL,
    [ActivitySrvDTLT]                         DATETIME           CONSTRAINT [DF_Activitytb_SrvDTLT] DEFAULT (getdate()) NULL,
    [ActivitySrvDTLTOffset]                   DATETIMEOFFSET (7) CONSTRAINT [DF_Activitytb_SrvDTLTOffset] DEFAULT (sysdatetimeoffset()) NULL,
    [ActivitySrcDTLT]                         DATETIME           NULL,
    [ActivityGPSType]                         VARCHAR (100)      NULL,
    [ActivityGPSSentence]                     VARCHAR (400)      NULL,
    [ActivityLatitude]                        FLOAT (53)         NULL,
    [ActivityLongitude]                       FLOAT (53)         NULL,
    [ActivityShape]                           [sys].[geography]  NULL,
    [ActivityComments]                        VARCHAR (500)      NULL,
    [ActivityType]                            VARCHAR (200)      NULL,
    [ActivityBatteryLevel]                    FLOAT (53)         NULL,
    [ActivityStartTime]                       DATETIME           NULL,
    [ActivityEndTime]                         DATETIME           NULL,
    [ActivityElapsedSec]                      INT                NULL,
    [ActivityTitle]                           VARCHAR (100)      CONSTRAINT [DF_Activitytb_ActivityTitle] DEFAULT ('') NULL,
    [ActivityBillingCode]                     VARCHAR (50)       CONSTRAINT [DF_Activitytb_ActivityBillingCode] DEFAULT ('') NULL,
    [ActivityCode]                            INT                CONSTRAINT [DF_Activitytb_ActivityCode] DEFAULT ('') NULL,
    [ActivityPayCode]                         INT                CONSTRAINT [DF_Activitytb_ActivityPayCode] DEFAULT ('') NULL,
    [ActivityArchiveFlag]                     BIT                CONSTRAINT [DF_Activitytb_ActivityArchiveFlag] DEFAULT ((0)) NULL,
    [ActivityCreateDate]                      DATETIME           CONSTRAINT [DF_Activitytb_ActivityCreateDate] DEFAULT (getdate()) NULL,
    [ActivityModifiedDate]                    DATETIME           NULL,
    [ActivityRevisionComments]                VARCHAR (500)      NULL,
    [ActivityGPSSource]                       VARCHAR (20)       NULL,
    [ActivityGPSTime]                         VARCHAR (10)       NULL,
    [ActivityFixQuality]                      INT                NULL,
    [ActivityNumberOfSatellites]              INT                NULL,
    [ActivityHDOP]                            FLOAT (53)         NULL,
    [ActivityAltitudemetersAboveMeanSeaLevel] FLOAT (53)         NULL,
    [ActivityHeightofGeoid]                   FLOAT (53)         NULL,
    [ActivityTimeSecondsSinceLastDGPS]        FLOAT (53)         NULL,
    [ActivityChecksumData]                    VARCHAR (10)       NULL,
    [ActivityBearing]                         FLOAT (53)         NULL,
    [ActivitySpeed]                           FLOAT (53)         NULL,
    [ActivityGPSStatus]                       VARCHAR (20)       NULL,
    [ActivityNumberOfGPSAttempts]             INT                NULL,
    CONSTRAINT [PK_Activitytb] PRIMARY KEY CLUSTERED ([ActivityID] ASC)
);

