CREATE TABLE [dbo].[rDropDown_Old] (
    [DropDownID]         INT            IDENTITY (1, 1) NOT NULL,
    [DropDownUID]        VARCHAR (100)  NULL,
    [ProjectID]          INT            NULL,
    [CreatedUserUID]     VARCHAR (100)  NULL,
    [ModifiedUserUID]    VARCHAR (100)  NULL,
    [CreateDTLT]         DATETIME       NULL,
    [ModifiedDTLT]       DATETIME       NULL,
    [InactiveDTLT]       DATETIME       NULL,
    [Comments]           VARCHAR (2000) NULL,
    [Revision]           INT            NULL,
    [ActiveFlag]         BIT            NULL,
    [DropDownType]       VARCHAR (50)   NULL,
    [FilterName]         VARCHAR (50)   NULL,
    [SortSeq]            INT            NULL,
    [FieldDisplay]       VARCHAR (200)  NULL,
    [FieldDescription]   VARCHAR (200)  NULL,
    [FieldType]          VARCHAR (200)  NULL,
    [FieldValue]         VARCHAR (200)  NULL,
    [DefaultFlag]        BIT            NULL,
    [DefaultType]        VARCHAR (200)  NULL,
    [DefaultValue]       VARCHAR (200)  NULL,
    [BreadcrumbFreq]     INT            NULL,
    [SurveyModeFlag]     BIT            NULL,
    [AdditionalStrData1] VARCHAR (50)   NULL,
    [AdditionalIntData1] INT            NULL,
    [AdditionalStrData2] VARCHAR (50)   NULL,
    [AdditionalIntData2] INT            NULL
);

