CREATE TABLE [dbo].[rDropDown] (
    [DropDownID]         INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DropDownUID]        VARCHAR (100)  NULL,
    [ProjectID]          INT            NULL,
    [CreatedUserUID]     VARCHAR (100)  NULL,
    [ModifiedUserUID]    VARCHAR (100)  NULL,
    [CreateDTLT]         DATETIME       CONSTRAINT [DF_r_DropDowns_CreateDTLT] DEFAULT (getdate()) NULL,
    [ModifiedDTLT]       DATETIME       NULL,
    [InactiveDTLT]       DATETIME       NULL,
    [Comments]           VARCHAR (2000) NULL,
    [Revision]           INT            CONSTRAINT [DF_r_DropDowns_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]         BIT            NULL,
    [DropDownType]       VARCHAR (50)   NULL,
    [FilterName]         VARCHAR (50)   NULL,
    [SortSeq]            INT            CONSTRAINT [DF_r_DropDowns_SortSeq] DEFAULT ((0)) NULL,
    [FieldDisplay]       VARCHAR (200)  NULL,
    [FieldDescription]   VARCHAR (200)  NULL,
    [FieldType]          VARCHAR (200)  NULL,
    [FieldValue]         VARCHAR (200)  NULL,
    [DefaultFlag]        BIT            NULL,
    [DefaultType]        VARCHAR (200)  NULL,
    [DefaultValue]       VARCHAR (200)  NULL,
    [BreadcrumbFreq]     INT            CONSTRAINT [DF_r_DropDowns_BreadcrumbFreq] DEFAULT ((60)) NULL,
    [SurveyModeFlag]     BIT            CONSTRAINT [DF_r_DropDowns_SurveyMode] DEFAULT ((0)) NULL,
    [AdditionalStrData1] VARCHAR (50)   NULL,
    [AdditionalIntData1] INT            NULL,
    [AdditionalStrData2] VARCHAR (50)   NULL,
    [AdditionalIntData2] INT            NULL,
    [OutValueNeededFlag] BIT            NULL,
    [SpecialFlag]        BIT            NULL,
    [OutValue]           VARCHAR (200)  NULL,
    [InValue]            VARCHAR (200)  NULL,
    [AltValue]           VARCHAR (200)  NULL,
    [StartDate]          DATE           NULL,
    [InactiveDate]       DATE           NULL,
    CONSTRAINT [PK_r_DropDowns] PRIMARY KEY CLUSTERED ([DropDownID] ASC)
);

