CREATE TABLE [dbo].[rgMapGridPipeline] (
    [FUNCTIONALLOCATION]   NVARCHAR (50)   NULL,
    [WORKCENTER]           NVARCHAR (10)   NULL,
    [OPERATION_AREA]       NVARCHAR (254)  NULL,
    [ROUTE_NAME]           NVARCHAR (254)  NULL,
    [FEATURE_TYPE]         NVARCHAR (561)  NULL,
    [LONG_ROUTE_NAME]      NVARCHAR (254)  NULL,
    [STATION_SERIES_ID]    NUMERIC (38, 8) NULL,
    [BEGIN_STATION]        NUMERIC (38, 8) NULL,
    [END_STATION]          NUMERIC (38, 8) NULL,
    [INSTALL_DATE]         DATETIME2 (7)   NULL,
    [INSTALL_JOB]          NVARCHAR (50)   NULL,
    [MATERIAL]             NVARCHAR (1525) NULL,
    [ROUTE_ID]             NUMERIC (38, 8) NULL,
    [LINE_ID]              NUMERIC (38, 8) NULL,
    [Lat_Begin]            NUMERIC (38, 8) NULL,
    [Long_Begin]           NUMERIC (38, 8) NULL,
    [Lat_End]              NUMERIC (38, 8) NULL,
    [Long_End]             NUMERIC (38, 8) NULL,
    [FID_LeakSurveyGrid]   INT             NULL,
    [MAPNUMBER]            NVARCHAR (10)   NULL,
    [PLATNUMBER]           NVARCHAR (10)   NULL,
    [MAPTYPE]              INT             NULL,
    [DISTRICT]             NVARCHAR (2)    NULL,
    [COUNTY]               NVARCHAR (15)   NULL,
    [PLATMAPNUMBER]        NVARCHAR (50)   NULL,
    [DIVISION]             INT             NULL,
    [LEGACYCOORDSYSWKID]   INT             NULL,
    [MAPNAME]              NVARCHAR (50)   NULL,
    [MAPTEMPLATE]          NVARCHAR (30)   NULL,
    [OFFICECODE]           NVARCHAR (3)    NULL,
    [SAPOBJECTID]          NVARCHAR (50)   NULL,
    [WALLMAP]              NVARCHAR (10)   NULL,
    [LASTLEAKSURVEY]       DATETIME2 (7)   NULL,
    [SCHEDULEDSURVEY]      DATETIME2 (7)   NULL,
    [LEAKSURVEYFREQUENCY]  NVARCHAR (20)   NULL,
    [METNAME]              NVARCHAR (50)   NULL,
    [SAPMAINTENANCESTATUS] NVARCHAR (10)   NULL
);

