CREATE TABLE [dbo].[rReport] (
    [ReportID]             INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ReportUID]            VARCHAR (100)  NOT NULL,
    [ProjectID]            INT            NOT NULL,
    [CreatedUserUID]       VARCHAR (100)  NOT NULL,
    [ModifiedUserUID]      VARCHAR (100)  NOT NULL,
    [CreateDTLT]           DATETIME       CONSTRAINT [DF_r_Reports_CreateDTLTOffset] DEFAULT (getdate()) NULL,
    [ModifiedDTLT]         DATETIME       NULL,
    [InactiveDTLT]         DATETIME       NULL,
    [Comments]             VARCHAR (2000) NULL,
    [Revision]             INT            CONSTRAINT [DF_r_Reports_Revision] DEFAULT ((0)) NOT NULL,
    [ActiveFlag]           BIT            NOT NULL,
    [ReportDisplayName]    VARCHAR (100)  NULL,
    [ReportDate]           DATE           NULL,
    [ReportInactiveDate]   DATE           NULL,
    [ReportType]           VARCHAR (200)  NULL,
    [ReportSPName]         VARCHAR (200)  NULL,
    [ReportDescription]    VARCHAR (2000) NULL,
    [ReportSortSeq]        INT            CONSTRAINT [DF_r_Reports_SortSeq] DEFAULT ((0)) NULL,
    [Parm]                 VARCHAR (500)  NULL,
    [ParmInspectorFlag]    BIT            NULL,
    [ParmDropDownFlag]     BIT            NULL,
    [ParmDateOverrideFlag] BIT            NULL,
    [ParmBetweenDateFlag]  BIT            NULL,
    [ParmDateFlag]         BIT            NULL,
    [ExportFlag]           BIT            NULL,
    CONSTRAINT [PK_r_Reports] PRIMARY KEY CLUSTERED ([ReportID] ASC)
);

