CREATE TABLE [dbo].[rUser] (
    [rUserID]           INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserUID]           VARCHAR (100)  NULL,
    [ProjectID]         INT            NULL,
    [CreatedUserUID]    VARCHAR (100)  NULL,
    [ModifiedUserUID]   VARCHAR (100)  CONSTRAINT [DF_r_Users_ModifiedUseruID] DEFAULT ('') NULL,
    [CreateDTLT]        DATETIME       CONSTRAINT [DF_r_Users_CreateDate] DEFAULT (getdate()) NULL,
    [ModifiedDTLT]      DATETIME       NULL,
    [InactiveDTLT]      DATETIME       NULL,
    [Comments]          VARCHAR (2000) NULL,
    [Revision]          INT            CONSTRAINT [DF_r_Users_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]        BIT            CONSTRAINT [DF_r_Users_ActiveFlag] DEFAULT ((1)) NULL,
    [UserInActiveFlag]  BIT            CONSTRAINT [DF_r_Users_InActiveFlag] DEFAULT ((0)) NULL,
    [UserLoginID]       VARCHAR (50)   NULL,
    [FirstName]         VARCHAR (50)   NULL,
    [LastName]          VARCHAR (50)   NULL,
    [LANID]             VARCHAR (20)   NULL,
    [Password]          VARCHAR (20)   NULL,
    [EmployeeType]      VARCHAR (200)  NULL,
    [EmployeePhone]     VARCHAR (20)   NULL,
    [CompanyName]       VARCHAR (200)  NULL,
    [CompanyPhone]      VARCHAR (20)   NULL,
    [SupervisorUserUID] VARCHAR (100)  NULL,
    [Salt]              VARCHAR (MAX)  NULL,
    [Hash]              VARCHAR (MAX)  NULL,
    [UserName]          VARCHAR (100)  CONSTRAINT [DF_rUser_UserName] DEFAULT ('') NULL,
    [UserAppRoleType]   VARCHAR (50)   CONSTRAINT [DF_rUser_UserAppRoleType] DEFAULT ('') NULL,
    [UserActiveFlag]    BIT            CONSTRAINT [DF_rUser_UserActiveFlag] DEFAULT ((1)) NULL,
    [UserArchiveFlag]   BIT            CONSTRAINT [DF_rUser_UserArchiveFlag] DEFAULT ((0)) NULL,
    [UserCreatedDate]   DATETIME       NULL,
    [UserCreatedBy]     INT            NULL,
    [UserModifiedDate]  DATETIME       NULL,
    [UserModifiedBy]    INT            NULL,
    CONSTRAINT [PK_r_Users] PRIMARY KEY CLUSTERED ([rUserID] ASC)
);

