CREATE TABLE [dbo].[tgAssetAddressInspection] (
    [AssetAddressInspectionID]        INT                IDENTITY (1, 1) NOT NULL,
    [AssetAddressInspectionUID]       VARCHAR (100)      NULL,
    [AssetAddressUID]                 VARCHAR (100)      NULL,
    [AssetInspectionUID]              VARCHAR (100)      NULL,
    [MapGridUID]                      VARCHAR (100)      NULL,
    [InspectionRequestUID]            VARCHAR (100)      NULL,
    [MasterLeakLogUID]                VARCHAR (100)      NULL,
    [CreatedUserUID]                  VARCHAR (100)      NULL,
    [ModifiedUserUID]                 VARCHAR (100)      NULL,
    [SourceID]                        VARCHAR (100)      NULL,
    [InGridFlag]                      BIT                CONSTRAINT [DF_tgAssetAddressInspection_InGridFlag] DEFAULT ((0)) NULL,
    [srvDTLT]                         DATETIME           CONSTRAINT [DF_tgAssetAddressInspection_srvDTLT] DEFAULT (getdate()) NULL,
    [srvDTLTOffset]                   DATETIMEOFFSET (7) CONSTRAINT [DF_tgAssetAddressInspection_srvDTLTOffset] DEFAULT (sysdatetimeoffset()) NULL,
    [srcDTLT]                         DATETIME           NULL,
    [Revision]                        INT                CONSTRAINT [DF_tgAssetAddressInspection_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]                      BIT                CONSTRAINT [DF_tgAssetAddressInspection_ActiveFlag] DEFAULT ((1)) NULL,
    [StatusType]                      VARCHAR (200)      CONSTRAINT [DF_tgAssetAddressInspection_StatusType] DEFAULT ('Active') NULL,
    [Latitude]                        FLOAT (53)         NULL,
    [Longitude]                       FLOAT (53)         NULL,
    [GPSSource]                       VARCHAR (20)       NULL,
    [GPSType]                         VARCHAR (20)       NULL,
    [GPSSentence]                     VARCHAR (400)      NULL,
    [GPSTime]                         VARCHAR (20)       NULL,
    [FixQuality]                      INT                CONSTRAINT [DF_tgAssetAddressInspection_FixQuality] DEFAULT ((0)) NULL,
    [NumberOfSatellites]              INT                CONSTRAINT [DF_tgAssetAddressInspection_NumberOfSatellites] DEFAULT ((0)) NULL,
    [HDOP]                            FLOAT (53)         NULL,
    [AltitudemetersAboveMeanSeaLevel] FLOAT (53)         NULL,
    [HeightofGeoid]                   FLOAT (53)         NULL,
    [TimeSecondsSinceLastDGPS]        FLOAT (53)         NULL,
    [ChecksumData]                    VARCHAR (10)       NULL,
    [Bearing]                         FLOAT (53)         NULL,
    [Speed]                           FLOAT (53)         NULL,
    [GPSStatus]                       VARCHAR (20)       NULL,
    [NumberOfGPSAttempts]             INT                CONSTRAINT [DF_tgAssetAddressInspection_NumberOfGPSAttempts] DEFAULT ((0)) NULL,
    [ActivityUID]                     VARCHAR (100)      NULL,
    [SrcOpenDTLT]                     DATETIME           NULL,
    [ElectrolysisSurveyFlag]          BIT                CONSTRAINT [DF_tgAssetAddressInspection_ElectrolysisSurveyFlag] DEFAULT ((0)) NULL,
    [RiserPipeSoilMeas]               VARCHAR (200)      NULL,
    [DIMPSurveyFlag]                  BIT                CONSTRAINT [DF_tgAssetAddressInspection_DIMPSurveyFlag] DEFAULT ((0)) NULL,
    [DIMPRiserType]                   VARCHAR (200)      NULL,
    [ServiceHeadAdapterType]          VARCHAR (200)      NULL,
    [ManifoldSetFlag]                 BIT                CONSTRAINT [DF_tgAssetAddressInspection_ManifoldSetFlag] DEFAULT ((0)) NULL,
    [ServiceValueFlag]                BIT                CONSTRAINT [DF_tgAssetAddressInspection_ServiceValueFlag] DEFAULT ((0)) NULL,
    [FilterFlag]                      BIT                CONSTRAINT [DF_tgAssetAddressInspection_FilterFlag] DEFAULT ((0)) NULL,
    [FilterSize]                      VARCHAR (200)      NULL,
    [FilterMfg]                       VARCHAR (200)      NULL,
    [FilterModel]                     VARCHAR (200)      NULL,
    [Regulator1Flag]                  BIT                CONSTRAINT [DF_tgAssetAddressInspection_Regulator1Flag] DEFAULT ((0)) NULL,
    [Regulator1Size]                  VARCHAR (200)      NULL,
    [Regulator1Mfg]                   VARCHAR (200)      NULL,
    [Regulator1Model]                 VARCHAR (200)      NULL,
    [Regulator2Flag]                  BIT                CONSTRAINT [DF_tgAssetAddressInspection_Regulator2Flag] DEFAULT ((0)) NULL,
    [Regulator2Size]                  VARCHAR (200)      NULL,
    [Regulator2Mfg]                   VARCHAR (200)      NULL,
    [Regulator2Model]                 VARCHAR (200)      NULL,
    [Regulator3Flag]                  BIT                CONSTRAINT [DF_tgAssetAddressInspection_Regulator3Flag] DEFAULT ((0)) NULL,
    [Regulator3Size]                  VARCHAR (200)      NULL,
    [Regulator3Mfg]                   VARCHAR (200)      NULL,
    [Regulator3Model]                 VARCHAR (200)      NULL,
    [MeterType]                       VARCHAR (200)      NULL,
    [MeterMfg]                        VARCHAR (200)      NULL,
    [MeterModel]                      VARCHAR (200)      NULL,
    [ECFlag]                          BIT                CONSTRAINT [DF_tgAssetAddressInspection_ECFlag] DEFAULT ((0)) NULL,
    [AMRFlag]                         BIT                CONSTRAINT [DF_tgAssetAddressInspection_AMRFlag] DEFAULT ((0)) NULL,
    [DripTankFlag]                    BIT                CONSTRAINT [DF_tgAssetAddressInspection_DripTankFlag] DEFAULT ((0)) NULL,
    [Photo1]                          VARCHAR (200)      NULL,
    [Photo2]                          VARCHAR (200)      NULL,
    [Photo3]                          VARCHAR (200)      NULL,
    CONSTRAINT [PK_tgAssetAddressInspection] PRIMARY KEY CLUSTERED ([AssetAddressInspectionID] ASC)
);



