CREATE TABLE [dbo].[tgAsset] (
    [AssetID]                  INT                IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AssetUID]                 VARCHAR (100)      NULL,
    [MapGridUID]               VARCHAR (100)      NULL,
    [ProjectID]                INT                NULL,
    [SourceID]                 VARCHAR (100)      NULL,
    [CreatedUserUID]           VARCHAR (100)      NULL,
    [ModifiedUserUID]          VARCHAR (100)      NULL,
    [SrcDTLT]                  DATETIME           NULL,
    [SrvDTLT]                  DATETIME           CONSTRAINT [DF_g_Assets_SrvDTLT] DEFAULT (getdate()) NULL,
    [SrvDTLTOffset]            DATETIMEOFFSET (7) CONSTRAINT [DF_g_Assets_SrvDTLTOffset] DEFAULT (sysdatetimeoffset()) NULL,
    [SrcOpenDTLT]              DATETIME           NULL,
    [SrcClosedDTLT]            DATETIME           NULL,
    [GPSType]                  VARCHAR (100)      NULL,
    [GPSSentence]              VARCHAR (400)      NULL,
    [Latitude]                 FLOAT (53)         NULL,
    [Longitude]                FLOAT (53)         NULL,
    [SHAPE]                    [sys].[geography]  NULL,
    [Comments]                 VARCHAR (2000)     NULL,
    [RevisionComments]         VARCHAR (500)      NULL,
    [Revision]                 INT                CONSTRAINT [DF_g_Assets_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]               BIT                CONSTRAINT [DF_tgAsset_ActiveFlag] DEFAULT ((1)) NULL,
    [StatusType]               VARCHAR (100)      CONSTRAINT [DF_g_Assets_StatusType] DEFAULT ('Active') NULL,
    [NewAssetFlag]             BIT                CONSTRAINT [DF_g_Assets_NewAssetFlag] DEFAULT ((0)) NULL,
    [NonAssetLocationFlag]     BIT                CONSTRAINT [DF_g_Assets_NonAssetLocationFlag] DEFAULT ((0)) NULL,
    [CGEFlag]                  BIT                CONSTRAINT [DF_g_Assets_CGEFlag] DEFAULT ((0)) NULL,
    [AOCFlag]                  BIT                CONSTRAINT [DF_g_Assets_AOCFlag] DEFAULT ((0)) NULL,
    [InspectFlag]              BIT                CONSTRAINT [DF_g_Assets_InspectFlag] DEFAULT ((0)) NULL,
    [LeakIndicationFlag]       BIT                CONSTRAINT [DF_g_Assets_LeakIndicationFlag] DEFAULT ((0)) NULL,
    [OtherIndicationFlag]      BIT                CONSTRAINT [DF_g_Assets_OtherIndicationFlag] DEFAULT ((0)) NULL,
    [Photo1]                   VARCHAR (250)      NULL,
    [Photo2]                   VARCHAR (250)      NULL,
    [Photo3]                   VARCHAR (250)      NULL,
    [OptionalData1]            VARCHAR (250)      NULL,
    [OptionalData2]            VARCHAR (250)      NULL,
    [OptionalData3]            VARCHAR (250)      NULL,
    [OptionalData4]            VARCHAR (250)      NULL,
    [OptionalData5]            VARCHAR (250)      NULL,
    [OptionalData6]            VARCHAR (250)      NULL,
    [OptionalData7]            VARCHAR (250)      NULL,
    [OptionalData8]            VARCHAR (250)      NULL,
    [OptionalData9]            VARCHAR (250)      NULL,
    [OptionalData10]           VARCHAR (250)      NULL,
    [OptionalData11]           VARCHAR (250)      NULL,
    [OptionalData12]           VARCHAR (250)      NULL,
    [ApprovedFlag]             BIT                NULL,
    [ApprovedByUserUID]        VARCHAR (100)      NULL,
    [ApprovedDTLT]             DATETIME           NULL,
    [SubmittedFlag]            BIT                NULL,
    [SubmittedStatusType]      VARCHAR (200)      NULL,
    [SubmittedUserUID]         VARCHAR (100)      NULL,
    [SubmittedDTLT]            DATETIME           NULL,
    [ResponseStatusType]       VARCHAR (200)      NULL,
    [Response]                 VARCHAR (500)      NULL,
    [ResponceErrorDescription] VARCHAR (500)      NULL,
    [ResponseDTLT]             DATETIME           NULL,
    [CompletedFlag]            BIT                NULL,
    [CompletedDTLT]            DATETIME           NULL,
    CONSTRAINT [PK_g_Assets] PRIMARY KEY CLUSTERED ([AssetID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'MapGrid.MapGridsUID', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tgAsset', @level2type = N'COLUMN', @level2name = N'MapGridUID';

