CREATE TABLE [dbo].[tgAssetAddressAOC] (
    [AssetAddressAOCID]               INT                IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AssetAddressAOCUID]              VARCHAR (100)      NULL,
    [AssetAddressUID]                 VARCHAR (100)      NULL,
    [AssetInspectionUID]              VARCHAR (100)      NULL,
    [InspectionRequestUID]            VARCHAR (100)      NULL,
    [MapGridUID]                      VARCHAR (100)      NULL,
    [ProjectID]                       INT                NULL,
    [SourceID]                        VARCHAR (50)       NULL,
    [CreatedUserUID]                  VARCHAR (100)      NULL,
    [ModifiedUserUID]                 VARCHAR (100)      NULL,
    [SrcDTLT]                         DATETIME           NULL,
    [SrvDTLT]                         DATETIME           CONSTRAINT [DF_g_AssetAOCs_SrvDTLT] DEFAULT (getdate()) NULL,
    [SrvDTLTOffset]                   DATETIMEOFFSET (7) CONSTRAINT [DF_g_AssetAOCs_SrvDTLTOffset] DEFAULT (sysdatetimeoffset()) NULL,
    [SrcOpenDTLT]                     DATETIME           NULL,
    [SrcClosedDTLT]                   DATETIME           NULL,
    [GPSType]                         VARCHAR (100)      NULL,
    [GPSSentence]                     VARCHAR (400)      NULL,
    [Latitude]                        FLOAT (53)         NULL,
    [Longitude]                       FLOAT (53)         NULL,
    [SHAPE]                           [sys].[geography]  NULL,
    [Comments]                        VARCHAR (2000)     NULL,
    [RevisionComments]                VARCHAR (500)      NULL,
    [Revision]                        INT                CONSTRAINT [DF_g_AssetAOCs_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]                      BIT                CONSTRAINT [DF_tgAssetAddressAOC_ActiveFlag] DEFAULT ((1)) NULL,
    [StatusType]                      VARCHAR (50)       CONSTRAINT [DF_g_AssetAOCs_StatusType] DEFAULT ('Active') NULL,
    [AOCType]                         VARCHAR (200)      NULL,
    [AOCReasonType]                   VARCHAR (200)      NULL,
    [AOCOther]                        VARCHAR (200)      NULL,
    [Photo1]                          VARCHAR (250)      NULL,
    [Photo2]                          VARCHAR (250)      NULL,
    [Photo3]                          VARCHAR (250)      NULL,
    [OptionalData1]                   VARCHAR (250)      NULL,
    [OptionalData2]                   VARCHAR (250)      NULL,
    [OptionalData3]                   VARCHAR (250)      NULL,
    [OptionalData4]                   VARCHAR (250)      NULL,
    [OptionalData5]                   VARCHAR (250)      NULL,
    [ApprovedFlag]                    BIT                CONSTRAINT [DF_tgAssetAddressAOC_ApprovedFlag] DEFAULT ((0)) NULL,
    [ApprovedByUserUID]               VARCHAR (200)      NULL,
    [ApprovedDTLT]                    DATETIME           NULL,
    [SubmittedFlag]                   BIT                CONSTRAINT [DF_tgAssetAddressAOC_SubmittedFlag] DEFAULT ((0)) NULL,
    [SubmittedStatusType]             VARCHAR (200)      NULL,
    [SubmittedUserUID]                VARCHAR (100)      NULL,
    [SubmittedDTLT]                   DATETIME           NULL,
    [ResponseStatusType]              VARCHAR (200)      NULL,
    [Responsecomments]                VARCHAR (500)      NULL,
    [ResponceErrorComments]           VARCHAR (500)      NULL,
    [ResponseDTLT]                    DATETIME           NULL,
    [CompletedFlag]                   BIT                CONSTRAINT [DF_tgAssetAddressAOC_CompletedFlag] DEFAULT ((0)) NULL,
    [CompletedDTLT]                   DATETIME           NULL,
    [DateFound]                       DATETIME           NULL,
    [MeterNumber]                     VARCHAR (50)       NULL,
    [GPSSource]                       VARCHAR (20)       NULL,
    [GPSTime]                         VARCHAR (20)       NULL,
    [FixQuality]                      INT                NULL,
    [NumberOfSatellites]              INT                NULL,
    [HDOP]                            FLOAT (53)         NULL,
    [AltitudemetersAboveMeanSeaLevel] FLOAT (53)         NULL,
    [HeightOfGeoid]                   FLOAT (53)         NULL,
    [TimeSecondsSinceLastDGPS]        FLOAT (53)         NULL,
    [ChecksumData]                    VARCHAR (10)       NULL,
    [Bearing]                         FLOAT (53)         NULL,
    [Speed]                           FLOAT (53)         NULL,
    [GPSStatus]                       VARCHAR (20)       NULL,
    [NumberOfGPSAttempts]             INT                NULL,
    [MasterLeakLogUID]                VARCHAR (100)      NULL,
    [ActivityUID]                     VARCHAR (100)      NULL,
    CONSTRAINT [PK_g_AssetAOCs] PRIMARY KEY CLUSTERED ([AssetAddressAOCID] ASC)
);





