CREATE TABLE [dbo].[tgAssetAddress] (
    [AssetAddressID]                  INT                IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AssetAddressUID]                 VARCHAR (100)      NULL,
    [AssetUID]                        VARCHAR (100)      NULL,
    [AssetInspectionUID]              VARCHAR (100)      NULL,
    [MapGridUID]                      VARCHAR (100)      NULL,
    [ProjectID]                       INT                NULL,
    [SourceID]                        VARCHAR (100)      NULL,
    [CreatedUserUID]                  VARCHAR (100)      NULL,
    [ModifiedUserUID]                 VARCHAR (100)      NULL,
    [SrcDTLT]                         DATETIME           NULL,
    [SrvDTLT]                         DATETIME           CONSTRAINT [DF_g_Address_SrvDTLT] DEFAULT (getdate()) NULL,
    [SrvDTLTOffset]                   DATETIMEOFFSET (7) CONSTRAINT [DF_g_AssetAddress_SrvDTLTOffset] DEFAULT (sysdatetimeoffset()) NULL,
    [GPSType]                         VARCHAR (100)      NULL,
    [GPSSentence]                     VARCHAR (400)      NULL,
    [Latitude]                        FLOAT (53)         NULL,
    [Longitude]                       FLOAT (53)         NULL,
    [SHAPE]                           [sys].[geography]  NULL,
    [Comments]                        VARCHAR (2000)     NULL,
    [RevisionComments]                VARCHAR (500)      NULL,
    [Revision]                        INT                CONSTRAINT [DF_g_AssetAddress_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]                      BIT                CONSTRAINT [DF_tgAssetAddress_ActiveFlag] DEFAULT ((1)) NULL,
    [StatusType]                      VARCHAR (100)      CONSTRAINT [DF_g_AssetAddress_StatusType] DEFAULT ('Active') NULL,
    [NewAssetFlag]                    BIT                CONSTRAINT [DF_g_AssetAddress_NewAssetFlag] DEFAULT ((0)) NULL,
    [NonAssetLocationFlag]            BIT                CONSTRAINT [DF_g_AssetAddress_NonAssetLocationFlag] DEFAULT ((0)) NULL,
    [AssetAddessCorrectionFlag]       BIT                CONSTRAINT [DF_g_AssetAddress_AssetCorrectionFlag] DEFAULT ((0)) NULL,
    [AssetIDNumberCorrectionFlag]     BIT                CONSTRAINT [DF_g_AssetAddress_AssetIDNumberCorrectionFlag] DEFAULT ((0)) NULL,
    [AssetConfirmFlag]                BIT                CONSTRAINT [DF_g_AssetAddress_AssetConfirmFlag] DEFAULT ((0)) NULL,
    [RouteNo]                         VARCHAR (200)      NULL,
    [RouteSeq]                        INT                NULL,
    [SortOrder]                       INT                NULL,
    [AssetAccountNo]                  VARCHAR (100)      NULL,
    [AssetAccountName]                VARCHAR (100)      NULL,
    [AssetName]                       VARCHAR (50)       NULL,
    [AssetLocationID]                 VARCHAR (200)      NULL,
    [AssetLocationCode]               VARCHAR (50)       NULL,
    [AssetIDStatus]                   VARCHAR (50)       NULL,
    [AssetIDNo]                       VARCHAR (50)       NULL,
    [AssetIDNoCorection]              VARCHAR (50)       NULL,
    [ReverseGeoHouseNo]               VARCHAR (50)       NULL,
    [ReverseGeoStreet1]               VARCHAR (100)      NULL,
    [ReverseGeoCity]                  VARCHAR (100)      NULL,
    [ReverseGeoState]                 VARCHAR (2)        NULL,
    [ReverseGeoZip]                   VARCHAR (10)       NULL,
    [ReverseGeoLat]                   FLOAT (53)         NULL,
    [ReverseGeoLong]                  FLOAT (53)         NULL,
    [ReverseGeoQuality]               VARCHAR (250)      NULL,
    [HouseNoNAFlag]                   BIT                NULL,
    [HouseNo]                         VARCHAR (100)      NULL,
    [Street1]                         VARCHAR (100)      NULL,
    [Street2]                         VARCHAR (100)      NULL,
    [AptSuite]                        VARCHAR (20)       NULL,
    [AptDesc]                         VARCHAR (50)       NULL,
    [Apt]                             VARCHAR (50)       NULL,
    [City]                            VARCHAR (50)       NULL,
    [State]                           VARCHAR (2)        NULL,
    [ZIP]                             VARCHAR (10)       NULL,
    [County]                          VARCHAR (255)      NULL,
    [CountyCode]                      VARCHAR (255)      NULL,
    [Photo1]                          VARCHAR (250)      NULL,
    [Photo2]                          VARCHAR (250)      NULL,
    [Photo3]                          VARCHAR (250)      NULL,
    [ApprovedFlag]                    BIT                NULL,
    [ApprovedByUserUID]               VARCHAR (100)      NULL,
    [ApprovedDTLT]                    DATETIME           NULL,
    [SubmittedFlag]                   BIT                NULL,
    [SubmittedStatusType]             VARCHAR (200)      NULL,
    [SubmittedUserUID]                INT                NULL,
    [SubmittedDTLT]                   DATETIME           NULL,
    [ResponseStatusType]              VARCHAR (200)      NULL,
    [Response]                        VARCHAR (500)      NULL,
    [ResponceErrorDescription]        VARCHAR (500)      NULL,
    [ResponseDTLT]                    DATETIME           NULL,
    [CompletedFlag]                   BIT                CONSTRAINT [DF_tgAssetAddress_CompletedFlag] DEFAULT ((0)) NULL,
    [CompletedDTLT]                   DATETIME           NULL,
    [GPSSource]                       VARCHAR (20)       NULL,
    [GPSTime]                         VARCHAR (20)       NULL,
    [FixQuality]                      INT                NULL,
    [NumberOfSatellites]              INT                NULL,
    [HDOP]                            FLOAT (53)         NULL,
    [AltitudemetersAboveMeanSeaLevel] FLOAT (53)         NULL,
    [HeightofGeoid]                   FLOAT (53)         NULL,
    [TimeSecondsSinceLastDGPS]        FLOAT (53)         NULL,
    [ChecksumData]                    VARCHAR (10)       NULL,
    [Bearing]                         FLOAT (53)         NULL,
    [Speed]                           FLOAT (53)         NULL,
    [GPSStatus]                       VARCHAR (20)       NULL,
    [NumberOfGPSAttempts]             INT                NULL,
    [AOCFlag]                         BIT                CONSTRAINT [DF_tgAssetAddress_AOCFlag] DEFAULT ((0)) NULL,
    [CGIFlag]                         BIT                CONSTRAINT [DF_tgAssetAddress_CGIFlag] DEFAULT ((0)) NULL,
    [InspectionRequestUID]            VARCHAR (100)      NULL,
    [MasterLeakLogUID]                VARCHAR (100)      NULL,
    [ActivityUID]                     VARCHAR (100)      NULL,
    [SrcOpenDTLT]                     DATETIME           NULL,
    [ReverseGeoLocationString]        VARCHAR (200)      NULL,
    CONSTRAINT [PK_g_AssetAddress] PRIMARY KEY CLUSTERED ([AssetAddressID] ASC)
);



