CREATE TABLE [dbo].[tInspectionRequest] (
    [tInspectionRequestID]      INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [InspectionRequestUID]      VARCHAR (100)  NOT NULL,
    [MapGridUID]                VARCHAR (100)  NULL,
    [ProjectID]                 INT            NULL,
    [SourceID]                  VARCHAR (100)  NULL,
    [CreatedUserUID]            VARCHAR (100)  CONSTRAINT [DF_tInspectionRequestCreatedUserID] DEFAULT ((999)) NOT NULL,
    [ModifiedUserUID]           VARCHAR (100)  NOT NULL,
    [CreateDTLT]                DATETIME       CONSTRAINT [DF_tInspectionRequestCreateDTLT] DEFAULT (getdate()) NULL,
    [ModifiedDTLT]              DATETIME       NULL,
    [Comments]                  VARCHAR (2000) NULL,
    [RevisionComments]          VARCHAR (500)  NULL,
    [Revision]                  INT            CONSTRAINT [DF_tInspectionRequestRevision] DEFAULT ((0)) NOT NULL,
    [ActiveFlag]                BIT            CONSTRAINT [DF_tInspectionRequest_ActiveFlag] DEFAULT ((1)) NOT NULL,
    [StatusType]                VARCHAR (100)  CONSTRAINT [DF_tInspectionRequestStatusType] DEFAULT ('Active') NULL,
    [PipelineType]              VARCHAR (200)  CONSTRAINT [DF_tInspectionRequestPipelineType] DEFAULT ('GD') NULL,
    [SurveyType]                VARCHAR (200)  NULL,
    [LsNtfNo]                   CHAR (12)      NULL,
    [OrderNo]                   VARCHAR (12)   NULL,
    [MapID]                     VARCHAR (9)    NULL,
    [Wall]                      VARCHAR (4)    NULL,
    [Plat]                      VARCHAR (4)    NULL,
    [MWC]                       VARCHAR (8)    NULL,
    [FLOC]                      VARCHAR (30)   NULL,
    [InspectionFrequencyType]   VARCHAR (200)  NULL,
    [ComplianceDueDate]         DATE           NULL,
    [ScheduledStartDate]        DATE           NULL,
    [ScheduledCompleteDate]     DATE           NULL,
    [ReleaseDate]               DATE           NULL,
    [PrevServ]                  BIGINT         NULL,
    [PrevFtOfMain]              BIGINT         NULL,
    [ReturnFlag]                BIT            NULL,
    [ReturnComments]            VARCHAR (2000) NULL,
    [FileCount]                 INT            NULL,
    [ApprovedFlag]              BIT            CONSTRAINT [DF_tInspectionRequest_ApprovedFlag] DEFAULT ((0)) NULL,
    [ApprovedByUserUID]         VARCHAR (100)  NULL,
    [ApprovedDTLT]              DATETIME       NULL,
    [SubmittedFlag]             BIT            CONSTRAINT [DF_tInspectionRequest_SubmittedFlag] DEFAULT ((0)) NULL,
    [SubmittedStatusType]       VARCHAR (200)  NULL,
    [SubmittedUserUID]          VARCHAR (100)  NULL,
    [SubmittedDTLT]             DATETIME       NULL,
    [ReturnedFlag]              BIT            CONSTRAINT [DF_tInspectionRequest_ReturnedFlag] DEFAULT ((0)) NULL,
    [ReturnedFromPGEStatusType] VARCHAR (200)  NULL,
    [RetrunedFromPGEDTLT]       DATETIME       NULL,
    [CompletedFlag]             BIT            CONSTRAINT [DF_tInspectionRequest_CompletedFlag] DEFAULT ((0)) NULL,
    [CompletedDTLT]             DATETIME       NULL,
    [InspectionType]            VARCHAR (20)   CONSTRAINT [DF_tInspectionRequest_InspectionType] DEFAULT ('TR') NULL,
    [ActualStartDate]           DATE           NULL,
    [AdhocFlag]                 BIT            CONSTRAINT [DF_tInspectionRequest_AdhocFlag] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_tInspectionRequest] PRIMARY KEY CLUSTERED ([tInspectionRequestID] ASC)
);




GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'INF002 Data Feed from PGE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tInspectionRequest', @level2type = N'COLUMN', @level2name = N'tInspectionRequestID';

