CREATE TABLE [dbo].[tInspectionRequest_Older] (
    [InspectionRequestID]      INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [InspectionRequestUID]     VARCHAR (100) NOT NULL,
    [MapGridUID]               VARCHAR (100) NOT NULL,
    [ProjectID]                INT           NOT NULL,
    [SourceID]                 VARCHAR (100) NULL,
    [CreatedUserUID]           VARCHAR (100) CONSTRAINT [DF_t_InspectionRequestsLog_CreatedUserID] DEFAULT ((0)) NOT NULL,
    [ModifiedUserUID]          VARCHAR (100) NOT NULL,
    [CreateDTLT]               DATETIME      CONSTRAINT [DF_t_InspectionRequestsLog_CreateDTLT] DEFAULT (getdate()) NULL,
    [ModifiedDTLT]             DATETIME      NULL,
    [Comments]                 VARCHAR (500) NULL,
    [RevisionComments]         VARCHAR (500) NULL,
    [Revision]                 INT           CONSTRAINT [DF_t_InspectionRequestsLog_Revision] DEFAULT ((0)) NOT NULL,
    [ActiveFlag]               BIT           NOT NULL,
    [StatusType]               VARCHAR (200) CONSTRAINT [DF_t_InspectionRequestsLog_StatusType] DEFAULT ('Active') NOT NULL,
    [CompanyNo]                VARCHAR (200) NULL,
    [Region]                   VARCHAR (200) NULL,
    [Division]                 VARCHAR (200) NULL,
    [Office]                   VARCHAR (200) NULL,
    [PipelineType]             VARCHAR (200) CONSTRAINT [DF_t_InspectionRequestsLog_PipelineType] DEFAULT ('GD') NULL,
    [SurveyType]               VARCHAR (200) NULL,
    [InspectionType]           VARCHAR (200) NULL,
    [InspectionFrequencyType]  VARCHAR (200) NULL,
    [MapGrid]                  VARCHAR (200) NULL,
    [RequestID]                VARCHAR (100) NULL,
    [ReleaseDate]              DATE          NULL,
    [ScheduledStartDate]       DATE          NULL,
    [ScheduledCompleteDate]    DATE          NULL,
    [ComplianceDueDate]        DATE          NULL,
    [Priority]                 VARCHAR (50)  NULL,
    [ApprovedFlag]             BIT           NULL,
    [ApprovedByUserUID]        VARCHAR (100) NULL,
    [ApprovedDTLT]             DATETIME      NULL,
    [SubmittedFlag]            BIT           NULL,
    [SubmittedStatusType]      VARCHAR (200) NULL,
    [SubmittedUserUID]         VARCHAR (100) NULL,
    [SubmittedDTLT]            DATETIME      NULL,
    [ResponseStatusType]       VARCHAR (200) NULL,
    [Response]                 VARCHAR (500) NULL,
    [ResponceErrorDescription] VARCHAR (500) NULL,
    [ResponseDTLT]             DATETIME      NULL,
    [CompletedFlag]            BIT           NOT NULL,
    [CompletedDTLT]            DATETIME      NULL,
    CONSTRAINT [PK_t_InspectionRequests] PRIMARY KEY CLUSTERED ([InspectionRequestID] ASC)
);

