CREATE TABLE [dbo].[tMasterLeakLog] (
    [tMasterLeakLogsID]        INT                IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MasterLeakLogUID]         VARCHAR (100)      NULL,
    [InspectionRequestLogUID]  VARCHAR (100)      NULL,
    [MapGridUID]               VARCHAR (100)      NULL,
    [ServiceDate]              DATE               NULL,
    [ProjectID]                INT                NULL,
    [SourceID]                 VARCHAR (100)      NULL,
    [CreatedUserUID]           VARCHAR (100)      NULL,
    [ModifiedUserUID]          VARCHAR (100)      NULL,
    [SrcDTLT]                  DATETIME           NULL,
    [SrvDTLTOffset]            DATETIMEOFFSET (7) CONSTRAINT [DF_t_MasterLeakLogs_SrvDTLTOffset] DEFAULT (sysdatetimeoffset()) NULL,
    [SrvDTLT]                  DATETIME           CONSTRAINT [DF_t_MasterLeakLog_SrvDTLT] DEFAULT (getdate()) NULL,
    [Comments]                 VARCHAR (2000)     NULL,
    [RevisionComments]         VARCHAR (500)      NULL,
    [Revision]                 INT                CONSTRAINT [DF_t_MasterLeakLogs_Revision] DEFAULT ((0)) NULL,
    [ActiveFlag]               BIT                CONSTRAINT [DF_tMasterLeakLog_ActiveFlag] DEFAULT ((1)) NULL,
    [StatusType]               VARCHAR (100)      CONSTRAINT [DF_t_MasterLeakLogs_StatusType] DEFAULT ('Not Approved') NULL,
    [ApprovedFlag]             BIT                CONSTRAINT [DF_tMasterLeakLog_ApprovedFlag] DEFAULT ((0)) NULL,
    [ApprovedByUserUID]        VARCHAR (100)      NULL,
    [ApprovedDTLT]             DATETIME           NULL,
    [SubmittedFlag]            BIT                CONSTRAINT [DF_tMasterLeakLog_SubmittedFlag] DEFAULT ((0)) NULL,
    [SubmittedStatusType]      VARCHAR (200)      NULL,
    [SubmittedUserUID]         VARCHAR (100)      NULL,
    [SubmittedDTLT]            DATETIME           NULL,
    [ResponseStatusType]       VARCHAR (200)      NULL,
    [Response]                 VARCHAR (500)      NULL,
    [ResponceErrorDescription] VARCHAR (500)      NULL,
    [ResponseDTLT]             DATETIME           NULL,
    [CompletedFlag]            BIT                CONSTRAINT [DF_tMasterLeakLog_CompletedFlag] DEFAULT ((0)) NULL,
    [CompletedDTLT]            DATETIME           NULL,
    CONSTRAINT [PK_t_MasterLeakLogs] PRIMARY KEY CLUSTERED ([tMasterLeakLogsID] ASC)
);

