CREATE TABLE [dbo].[zpgeDistributionPlatIntersetTransmissionMainExcelFile] (
    [ID]                            FLOAT (53)     NULL,
    [OPERATION_AREA]                NVARCHAR (255) NULL,
    [ROUTE_NAME]                    NVARCHAR (255) NULL,
    [LONG_ROUTE_NAME]               NVARCHAR (255) NULL,
    [STATION_SERIES_ID]             FLOAT (53)     NULL,
    [TRANS_DEF]                     NVARCHAR (255) NULL,
    [FACILITY_TYPE_DESC]            NVARCHAR (255) NULL,
    [FEATURE_TYPE]                  NVARCHAR (255) NULL,
    [BEGIN_STATION]                 FLOAT (53)     NULL,
    [END_STATION]                   FLOAT (53)     NULL,
    [PIPE_LENGTH]                   FLOAT (53)     NULL,
    [DOT_CLASS]                     NVARCHAR (255) NULL,
    [INSTALL_DATE]                  DATETIME       NULL,
    [INSTALL_JOB]                   FLOAT (53)     NULL,
    [MATERIAL]                      NVARCHAR (255) NULL,
    [OUTSIDE_DIAMETER]              FLOAT (53)     NULL,
    [WALL_THICKNESS]                FLOAT (53)     NULL,
    [SMYS]                          FLOAT (53)     NULL,
    [PIPE_GRADE]                    NVARCHAR (255) NULL,
    [LONG_SEAM]                     NVARCHAR (255) NULL,
    [MANUFACTURER]                  NVARCHAR (255) NULL,
    [ASSET_OWNER]                   NVARCHAR (255) NULL,
    [MAINT_ORG]                     NVARCHAR (255) NULL,
    [HCA_IMPACT_RADIUS]             FLOAT (53)     NULL,
    [LEAK_SURVEY_GROUP]             NVARCHAR (255) NULL,
    [LEAK_SURVEY_FREQUENCY]         NVARCHAR (255) NULL,
    [JOINT_TYPE]                    NVARCHAR (255) NULL,
    [BEND_RADIUS]                   NVARCHAR (255) NULL,
    [BEND_ORIENTATION]              NVARCHAR (255) NULL,
    [BEND_ANGLE]                    NVARCHAR (255) NULL,
    [PFL_COATING_TYPE]              NVARCHAR (255) NULL,
    [PFL_COATING_DATE]              DATETIME       NULL,
    [COATING_CONDITION]             NVARCHAR (255) NULL,
    [CP_SURVEY_GROUP]               NVARCHAR (255) NULL,
    [PFL_FILENAME]                  NVARCHAR (255) NULL,
    [PFL_FEATURE_NUM]               FLOAT (53)     NULL,
    [ROUTE_ID]                      FLOAT (53)     NULL,
    [Adjacent Plat East]            NVARCHAR (255) NULL,
    [Adjacent Plat North]           NVARCHAR (255) NULL,
    [Adjacent Plat Northeast]       NVARCHAR (255) NULL,
    [Adjacent Plat Northwest]       NVARCHAR (255) NULL,
    [Adjacent Plat South]           NVARCHAR (255) NULL,
    [Adjacent Plat Southeast]       NVARCHAR (255) NULL,
    [Adjacent Plat Southwest]       NVARCHAR (255) NULL,
    [Adjacent Plat West]            NVARCHAR (255) NULL,
    [Conversion ID]                 FLOAT (53)     NULL,
    [Conversion Work Package]       NVARCHAR (255) NULL,
    [Create Date]                   DATETIME       NULL,
    [Create User]                   NVARCHAR (255) NULL,
    [District]                      FLOAT (53)     NULL,
    [Functional Location]           NVARCHAR (255) NULL,
    [Legacy Coordinate System WKID] FLOAT (53)     NULL,
    [Map Name]                      NVARCHAR (255) NULL,
    [Map Template]                  NVARCHAR (255) NULL,
    [County]                        NVARCHAR (255) NULL,
    [Division]                      FLOAT (53)     NULL,
    [Map Type]                      FLOAT (53)     NULL,
    [Office Code]                   NVARCHAR (255) NULL,
    [Wall Map]                      FLOAT (53)     NULL,
    [Plat Number]                   NVARCHAR (255) NULL,
    [Plat Map Number]               NVARCHAR (255) NULL,
    [SAP ObjectID]                  NVARCHAR (255) NULL,
    [Update User]                   NVARCHAR (255) NULL,
    [Work Center]                   NVARCHAR (255) NULL,
    [Symbol Scale]                  FLOAT (53)     NULL,
    [Met Name]                      NVARCHAR (255) NULL,
    [100 Scale Plat Number]         NVARCHAR (255) NULL,
    [SAP Maintenance Status]        NVARCHAR (255) NULL,
    [Plat Map Hyperlink]            NVARCHAR (255) NULL,
    [Shape_Length]                  FLOAT (53)     NULL
);

